apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      tier: frontend      
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          env:
          {{- with  .Values.dbenv }}
            {{- . | toYaml | nindent 10 -}}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 10 }}
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          volumeMounts:
          - name: wordpress-persistent-storage
            mountPath: /var/www/html/wordpress
          volumes:
          - name: wordpress-persistent-storage
            persistentVolumeClaim:
              claimName: wordpress-pv-claim