# Default values for wordpress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: frame0310/IT-Academy-project
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  #tag: v0.0.24

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""



service:
  name: wordpress-front
  type: ClusterIP
  ports:
    http: 80

ingress:
    annotations:
    kubernetes.io/ingress.class: nginx
    hosts:
    - host: wordpress-poject.k8s-15.sa
      paths:
        - path: /
          pathType: ImplementationSpecific

pvc:
  storage: 2Gi
  type: nfs 

pv:
  storage: 5Gi
  type: nfs

nfs:
  server: 192.168.37.105
  path: /mnt/IT-Academy/nfs-data/sa2-22-22/ssechkov/wordpress/

dbenv:
  - name: DB_HOST
    value: 192.168.202.33:3306
  - name: DB_NAME
    value: wordpress_db1
  - name: DB_USER
    value: wordpress_user1
  - name: DB_PASSWORD
    value: wordpress_pass1


resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   limits:
     cpu: 200m
     memory: 256Mi
   requests:
     cpu: 200m
     memory: 256Mi